name: Deploy Identity Service to Render with Docker

on:
  push:
    branches:
      - main  # Trigger when commits are pushed to the main branch

jobs:
  docker-build-push:
    runs-on: ubuntu-latest
    environment: demo

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Step 3: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: docker.io

      # Step 4: Build the Docker image
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/identity-app:latest .

      # Step 5: Push Docker image to Docker Hub
      - name: Push Docker image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/identity-app:latest

  deploy-to-render:
    needs: docker-build-push
    runs-on: ubuntu-latest
    environment: demo

    steps:
      # Step 6: Deploy to Render using API
      - name: Deploy to Render
        run: |
          echo "Deploying to Render..."
          curl -X POST "https://api.render.com/v1/services?limit=20" \
            -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
            -H "Accept: application/json" \
            -o services.json

          echo "Checking for service ID..."
          cat services.json

          # Attempt direct deploy without service ID
          echo "Triggering deployment..."
          RESPONSE=$(curl -X POST "https://api.render.com/v1/deploys" \
            -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
            -H "Content-Type: application/json" \
            -d '{
              "type": "docker_image",
              "imageURL": "${{ secrets.DOCKER_USERNAME }}/identity-app:latest",
              "serviceId": "identity-service"
            }')

          echo "Deployment response: $RESPONSE"
