name: Deploy Identity Service to Render with Docker

on:
  push:
    branches:
      - main  # Trigger when commits are pushed to the main branch

jobs:
  docker-build-push:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Step 3: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 4: Build the Docker image
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/identity-app:latest .

      # Step 5: Push Docker image to Docker Hub
      - name: Push Docker image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/identity-app:latest

  deploy-to-render:
    needs: docker-build-push
    runs-on: ubuntu-latest

    steps:
      # Step 6: Log in to Render (không cần bước này)
      - name: Check Render API Key
        run: |
          if [ -z "${{ secrets.RENDER_API_KEY }}" ]; then
            echo "RENDER_API_KEY is not set. Please add it to your repository secrets."
            exit 1
          else
            echo "RENDER_API_KEY is set. Proceeding with deployment."
          fi

      # Step 7: Deploy image from Docker Hub to Render
      - name: Deploy to Render
        run: |
          # Sử dụng API endpoint chính xác của Render
          SERVICE_ID="srv-d078g6rubrs73f8t7"

          # Kiểm tra xem có thể lấy thông tin dịch vụ không
          echo "Checking service information..."
          SERVICE_INFO=$(curl -s -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
            "https://api.render.com/v1/services/$SERVICE_ID")

          if [[ $SERVICE_INFO == *"id"* ]]; then
            echo "Service found, triggering deployment..."
            curl -X POST "https://api.render.com/v1/services/$SERVICE_ID/deploys" \
              -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
              -H "Content-Type: application/json" \
              -d '{
                "clearCache": "clear"
              }'
            echo "Deployment triggered successfully"
          else
            echo "Service not found or API key issue. Response: $SERVICE_INFO"
            echo "Continuing workflow but deployment may have failed"
          fi

      # Step 8: Verify deployment
      - name: Wait for deployment and verify
        run: |
          echo "Waiting for deployment to complete..."
          sleep 60
          echo "Verifying deployment..."
          # Sử dụng URL thực tế của dịch vụ của bạn
          SERVICE_URL="https://identity-service-ixvs.onrender.com"
          RESPONSE=$(curl -s $SERVICE_URL/cicd-check || echo "Failed to connect")
          echo "Response from service: $RESPONSE"
          if [[ $RESPONSE == *"CI/CD pipeline is working correctly"* ]]; then
            echo "✅ CI/CD verification successful!"
          else
            echo "❌ CI/CD verification failed or service not yet available"
            echo "This is expected on the first run when the endpoint doesn't exist yet"
            # Không fail workflow nếu endpoint chưa sẵn sàng
            echo "Continuing anyway to complete the workflow"
          fi
